### PR TITLE
Partial translation [workflows.md] indonesian

### PR DESCRIPTION
**Pull request by raja-rizki**

### CODE REVIEW

**Comment by raja-rizki** [comment]
please respond
It's been days

**Comment by yurikuzn** [comment]
Please create translated files in i18n/id_ID directory.

**Comment by yurikuzn** [comment]
We have this file already translated https://github.com/espocrm/documentation/blob/master/i18n/id_ID/administration/workflows.md

**Comment by raja-rizki** [comment]
I will look for a new translation, thanks :)

**Comment by raja-rizki** [comment]
it seems the translation file is lacking and already in use, i am very sad

**Pull request closed without merging**
