### PR TITLE
Tagalog Localization #1 

### PR DESCRIPTION
**Pull request by cordeta**
[Changes applied] 
Corrected all the misspelled words and suggested new words that would fit the translation better

@yurikuzn

### CODE REVIEW

**Comment by yurikuzn** [comment]
Could you make links in readme.md file to follow to translated files. Thanks.

**Comment by cordeta** [comment]
Okay . I will add links starting this moment . I followed on of tagalog collaborator . Sorry for not mentioning the directory here. Thanks

**Comment by cordeta** [comment]
@yurikuzn  regarding for your request . What am i supposed to do ? Still confused sorry. Are you asking that i whould put the links of the files that i changed here?

**Comment by yurikuzn** [comment]
Links in the file https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/README.md leads to English language pages.  Need to add 'i18n/tl_PH/' inside all links.

**Pull request merged**
