### PR TITLE
translation to Spanish for entity-manager.md

### PR DESCRIPTION
**Pull request by focusedguy**
part 2 of 2. more than 1000 words achieved with both translations

### CODE REVIEW

**Comment by yurikuzn** [comment]
Hi,

We can merge only if you create translated files in i18n/es_ES directory. Bur there is already that file translated.

**Comment by focusedguy** [comment]
How can I see the already translated files? 

When I edited it, it was not translated, it was in English?

**Comment by yurikuzn** [comment]
Here are files translated to Spanish https://github.com/espocrm/documentation/tree/master/i18n/es_ES/administration

**Comment by focusedguy** [comment]
Are there still files that needs Spanish translations?

**Comment by yurikuzn** [comment]
Seems there is no any.

**Pull request closed without merging**
