### PR TITLE
browser-support.md

### PR DESCRIPTION
**Pull request by nunojesus**
Hello,
I made the Portuguese translation of this file.
 Hope you find it useful!
Greetings
Nuno Jesus

### CODE REVIEW

**Comment by yurikuzn** [comment]
Thanks. I moved file to: https://github.com/espocrm/documentation/blob/master/i18n/pt_PT/user-guide/browser-support.md

**Comment by nunojesus** [comment]
Hi, Im new in this stuff :) 

The next pull request (translations) you will merged to https://github.com/espocrm/documentation/tree/master/i18n/pt_PT/user-guide ? Thank you!

**Comment by yurikuzn** [comment]
Yep.

**Comment by nunojesus** [comment]
Thank you for your comment. If you want I can make also de translation to portuguese from brazil. Greetings Nuno

**Pull request closed without merging**
