### PR TITLE
italian translation of upgrading.md file

### PR DESCRIPTION
**Pull request by mdesantiago41**
please check

### CODE REVIEW

**Comment by yurikuzn** [comment]
Could you create the file i18n/it_IT/administration/upgrading.md. Thanks

**Comment by mdesantiago41** [comment]
Done

**Comment by mdesantiago41** [comment]
Thanks

**Comment by yurikuzn** [comment]
I moved it in the right place. Please check https://github.com/espocrm/documentation/blob/master/i18n/it_IT/administration/upgrading.md

**Comment by mdesantiago41** [comment]
Thanks

**Comment by mdesantiago41** [comment]
please merged

**Comment by mdesantiago41** [comment]
merged please

**Pull request closed without merging**
